apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.port }}
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://backend:5000"
        {{- with .Values.frontend.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 8 }}
        {{- else }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.frontend.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
        {{- end }}
        {{- with .Values.frontend.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 8 }}
        {{- else }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.frontend.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
        {{- end }}
        {{- with .Values.frontend.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
