name: CI - Helm Lint + SonarQube

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Helm Lint
        run: |
          mkdir -p artifacts
          helm lint helm/focus-flow | tee artifacts/helm-lint.txt

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.service_name }}
            -Dsonar.sources=${{ inputs.service_path }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload CI Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts-${{ inputs.service_name }}
          path: artifacts/
