name: Focus-Flow CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml

  docker:
    needs: ci
    uses: ./.github/workflows/docker-template.yml
    with:
      tag: ${{ github.run_number }}
    secrets: inherit

  deploy:
    needs: docker
    uses: ./.github/workflows/deploy-template.yml
    with:
      tag: ${{ github.run_number }}
    secrets: inherit
