name: Focus-Flow CI/CD

on:
  push:
    branches:
      - main
      - dev
      
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  backend-ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service_name: focus-flow-backend
      service_path: backend
    secrets: inherit

  frontend-ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service_name: focus-flow-frontend
      service_path: frontend
    secrets: inherit

  task-read-ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service_name: focus-flow-task-read
      service_path: backend/task-read-service
    secrets: inherit

  task-write-ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service_name: focus-flow-task-write
      service_path: backend/task-write-service
    secrets: inherit

  docker:
    if: github.event_name != 'pull_request'
    needs:
      - backend-ci
      - frontend-ci
      - task-read-ci
      - task-write-ci
    uses: ./.github/workflows/docker-template.yml
    with:
      tag: ${{ github.run_number }}
    secrets: inherit

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: docker
    uses: ./.github/workflows/deploy-template.yml
    with:
      tag: ${{ github.run_number }}
      environment: ${{ github.event.inputs.environment || 'prod' }}
    secrets: inherit
